### ISSUE TITLE
REPORTE DE PRACTICA1 ADOBE XD

### ISSUE THREAD

**Issue by OFELHER93** [SistemasTecTlaxiaco/practicaprototipos-topicosadobexd#2]
[Reporte de practica 1.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-topicosadobexd-MJO/files/8066561/Reporte.de.practica.1.pdf)
https://xd.adobe.com/view/29f049e1-9629-4155-8c9f-9f7de0dafc35-7ca3/

**Comment by josealfredo79** [comment]
Falta la calificación

**Comment by josealfredo79** [comment]
Nuevamente indico hace falta la calificacion

**Comment by Yareli-Perez** [comment]
calificación =82

**Comment by josealfredo79** [comment]
La calificación deben aplicar una regla de tres
